sudo: required
dist: xenial
language: c
compiler:
  - gcc

deploy:
  provider: releases
  api_key:
    secure: "V1vhyc4D4Czy8gM5OakKfdBGJ/YEdfsuOpJcFSmwFCz6RJYPROGXRDI6srU2L2wpvIVU0z+9wJ2VDXuspqzaCNlZST1HPNZxHNDm3BsbJrEHpaQ806T4msMH+QzrI2I++dGtG52xvFXaNDL5C1cEple4q5zDoSlQ1umfD5wDQHTy0KMwIOXRbT0yO4bF5nKAtWhbiRmg4jjd7Io5NYRPo4OR8eDOQJNQSQAjdWEgdoOSK9p76OKJxN127O5cR2EYXDu4NEg1JH3ta+FlVrH9/nvC6sORYaLDOBk+tk6IflggSlUqi+oJakLBMCI5OvIX0duBbsuLPI+5YtvwVSNQbcA1gFu+0hMEeu6Ev1sZTv8uhJchoSDrMSlNKlHeAE1nYJuqIsTybyCxAR9qeViKEIhNn+WC0PijrgcVodXlE2ydh7fhla1ehLt/q+wpEjlq5PCZnhu2RCXhnIqBhmTcTFPsC0C6dkzHivmOAlMjDBtHtStI22EhvGXZAvDsSLvLjMBbAUiFmpC7ORlF+W/w00r75BangRtaj4KHEuEIvdtWUxDxCqqSIFiS4lIh8ajW/O2CgJODWBm7CDi1092jv7M4kIA4IpL4uvt0FJhppUZvyfPdO2YgN1Uv9Dko5Qu5PJp6vF57QJwU3yFsSnU9lQRu54XHlQCjBKnzvTrA56g="
  file:
  - $(ls -d1 bin/*/* | tr "\n" ":")
  skip_cleanup: true
  draft: true
  on:
    tags: true

before_script:
  - (wget https://s3.amazonaws.com/adafruit-circuit-python/gcc-arm-embedded_7-2018q2-1~xenial1_amd64.deb && sudo dpkg -i gcc-arm-embedded*_amd64.deb)
  - (wget https://www.nordicsemi.com/api/sitecore/Products/DownloadPlatform --post-data=fileid=8F19D314130548209E75EFFADD9348DB -O cli-tools.tar && tar -xv -f cli-tools.tar && mv mergehex mergehex_all && mv mergehex_all/mergehex .)
  - export PATH=.:$PATH
  - mergehex --version

  # report some good version numbers to the build
  - gcc --version
  - arm-none-eabi-gcc --version
  - python3 --version
  - python --version
  - sudo apt-get install -y python3-pip python3-setuptools
  - pip3 install --user adafruit-nrfutil

script:
  - python3 tools/build_all.py
