name: Build

on:
  pull_request:
  push:
  repository_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          # Adafruit Boards
          - 'circuitplayground_nrf52840'
          - 'clue_nrf52840'
          - 'feather_nrf52832'
          - 'feather_nrf52840_express'
          - 'feather_nrf52840_sense'
          - 'itsybitsy_nrf52840_express'
          - 'metro_nrf52840_express'
          # Alphabetical order
          - 'ADM_B_NRF52840_1'
          - 'ae_bl652_bo'
          - 'aramcon_badge_2019'
          - 'arcade_feather_nrf52840_express'
          - 'arduino_nano_33_ble'
          - 'bast_ble'
          - 'bluemicro_nrf52840'
          - 'electronut_labs_papyr'
          - 'ikigaisense_vita'
          - 'mdk_nrf52840_dongle'
          - 'nice_nano'
          - 'nrf52840_m2'
          - 'ohs2020_badge'
          - 'particle_argon'
          - 'particle_boron'
          - 'particle_xenon'
          - 'pca10056'
          - 'pca10059'
          - 'pca10100'
          - 'pitaya_go'
          - 'raytac_mdbt50q_rx'
          - 'waveshare_nrf52840_eval'

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true      
        
    - name: Install Toolchains
      run: |
        pip3 install adafruit-nrfutil uritemplate requests intelhex
        npm install --global xpm
        # 9.3.1-1.2.1 is xpack modified version which significantly increased compiled size to 6-7KB and cause flash overflow.
        # Skip this version for now, we will try again with next official release from ARM
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@9.3.1-1.1.1
        echo `echo $HOME/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin` >> $GITHUB_PATH
    
    - name: Build
      run: make BOARD=${{ matrix.board }}
      
    - name: Upload Release Asset
      if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested')
      working-directory: tools
      env:
        UPLOAD_URL: ${{ github.event.release.upload_url }}
        ADABOT_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "[ -z \"$ADABOT_GITHUB_ACCESS_TOKEN\" ] || python3 -u upload_release_files.py"
      
